wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1637408903
    t:
      1:
      - 1
      4: 3.7.4
      5: 0.12.6
      8:
      - 1
      - 5
